name: Build Master in docker

on:
  pull_request:
    branches:
      - 'llvm-16.0.6'
  push:
    branches:
      - 'llvm-16.0.6'

env:
  OPAMROOT: /home/opam/.opam
  OPAMYES: true
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:ubuntu-lts-ocaml-4.14
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add LLVM repository
        run: |
            echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main" | 
                sudo dd of=/etc/apt/sources.list.d/llvm-toolchain-jammy-16.list
            curl https://apt.llvm.org/llvm-snapshot.gpg.key |
                gpg --dearmor                               |
                sudo dd of=/etc/apt/trusted.gpg.d/llvm-snapshot.gpg
            sudo apt-get update

      - name: Set up c++ compiler
        run: |
            sudo apt-get install clang-16 -y
            echo "CXX=clang++-16" >> $GITHUB_ENV

      - name: Installing dependencies
        run: |
            sudo apt-get install llvm-16-dev llvm-16-tools libmlir-16-dev mlir-16-tools -y
            opam pin add ./ -n
            opam depext mlir -y
            opam install . --deps-only --with-test --with-doc

      - name: Building
        run: |
            opam exec -- dune build --profile=release
            opam exec -- dune build @install --profile=release
      
      - name: Running tests
        run: opam exec -- dune runtest --profile=release

      - name: Send coverage report to Coveralls
        if: github.event_name != 'pull_request'
        run: |
          git config --global --add safe.directory /__w/ocaml-mlir/ocaml-mlir
          opam exec -- make coverage
          opam exec -- bisect-ppx-report send-to Coveralls --coverage-path $BISECT_DIR
        env:
          BISECT_DIR: /tmp/mlircov
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
